import { useDeckStore } from "./card-deck/card-deck-store/card-deck.store";

const funFacts = [
  "La mémoire n’est pas un “enregistreur” : chaque souvenir est une reconstruction, pas une copie fidèle de la réalité.",
  "Se souvenir modifie le souvenir : chaque rappel altère légèrement la mémoire, un peu comme une sauvegarde écrasée.",
  "Oublier est normal et utile : le cerveau élimine des informations pour éviter la saturation.",
  "On oublie très vite sans révision : une grande partie de ce qu’on apprend disparaît en 24–48 h (courbe de l’oubli).",
  "La mémoire humaine n’a pas de “taille maximale” connue.",
  "La mémoire dépend fortement du contexte (lieu, odeur, musique, humeur).",
  "Le stress modéré améliore la mémoire, mais le stress intense la détériore.",
  "La mémoire est distribuée : il n’existe pas un seul “centre de la mémoire” dans le cerveau.",
  "Le cerveau encode surtout ce qui a du sens, pas ce qui est neutre.",
  "L’émotion est un puissant amplificateur de mémoire.",
  "La mémoire sensorielle dure moins d’une seconde (vision, audition).",
  "La mémoire de travail (celle qui permet de garder temporairement des informations en tête pour raisonner ou manipuler) est très limitée : environ 4 à 7 éléments.",
  "La mémoire à long terme peut durer toute une vie.",
  "La mémoire procédurale concerne les savoir-faire automatiques (comme faire du vélo ou nouer ses lacets) et elle est très résistante à l’oubli.",
  "On peut perdre les souvenirs de sa propre vie (mémoire autobiographique) sans perdre ses compétences ou savoir-faire.",
  "La mémoire déclarative (qui concerne les faits et événements qu’on peut raconter consciemment) est plus fragile que la mémoire motrice (qui permet d’accomplir des gestes ou mouvements sans avoir besoin d’y penser, comme faire du vélo).",
  "Les souvenirs d’enfance avant 3–4 ans sont rares (amnésie infantile).",
  "La mémoire prospective sert à se souvenir de faire quelque chose plus tard.",
  "La mémoire épisodique concerne les événements vécus.",
  "La mémoire sémantique stocke les connaissances générales.",
  "Dormir consolide la mémoire.",
  "Une nuit blanche empêche la fixation des souvenirs.",
  "Les rêves participent à la consolidation de la mémoire.",
  "Les siestes améliorent l’apprentissage.",
  "Le cerveau “rejoue” les souvenirs pendant le sommeil.",
  "Le manque de sommeil affecte surtout la mémoire récente.",
  "Apprendre juste avant de dormir aide à mémoriser.",
  "Le sommeil profond est crucial pour la mémoire factuelle (c’est-à-dire la mémoire des connaissances, comme des faits, des mots ou des concepts).",
  "Le sommeil paradoxal (période des rêves) consolide surtout les souvenirs liés aux émotions, en renforçant l’aspect émotionnel des expériences.",
  "Le cerveau trie les souvenirs pendant la nuit.",
  "On peut créer de faux souvenirs très convaincants.",
  "Les témoignages oculaires sont souvent peu fiables.",
  "La mémoire est influençable par des questions mal formulées.",
  "On peut être sûr à 100 % d’un souvenir faux.",
  "Le cerveau comble les trous sans qu’on s’en rende compte.",
  "Les souvenirs répétés deviennent plus “solides”, vrais ou faux.",
  "Les photos peuvent modifier nos souvenirs.",
  "Raconter un souvenir le transforme.",
  "L’imagination peut être confondue avec la mémoire.",
  "Les souvenirs anciens semblent plus clairs qu’ils ne l’étaient réellement.",
  "Sans attention, il n’y a presque pas de mémoire.",
  "Le multitâche réduit fortement la mémorisation.",
  "Se tester soi-même améliore la mémoire.",
  "Espacer les révisions est plus efficace que bachoter.",
  "Expliquer à quelqu’un renforce la mémoire.",
  "Faire des erreurs aide à mieux apprendre.",
  "Le cerveau retient mieux ce qui est inhabituel.",
  "Les analogies facilitent la mémorisation.",
  "L’apprentissage actif est bien plus efficace que passif.",
  "La mémoire ne décline pas uniformément avec l’âge.",
  "La mémoire des noms propres est la plus fragile.",
  "Les souvenirs émotionnels résistent mieux au vieillissement.",
  "Les personnes âgées apprennent encore très bien.",
  "La mémoire procédurale (mémoire des gestes ou habitudes comme faire du vélo, écrire, conduire) reste souvent intacte, même quand d’autres types de mémoire déclinent.",
  "Les jeunes adultes atteignent un pic de mémoire épisodique, c’est-à-dire la capacité à se souvenir d’événements vécus avec leurs contextes (où, quand, avec qui).",
  "Les enfants ont une excellente mémoire implicite (celle qui permet d’apprendre sans en avoir conscience, comme acquérir des règles de grammaire ou reconnaître des motifs).",
  "La mémoire autobiographique (celle qui concerne les souvenirs personnels de sa propre vie) se stabilise vers 20–30 ans.",
  "Le cerveau garde sa capacité à se modifier et à s’adapter (plasticité cérébrale) tout au long de la vie.",
  "Certaines personnes ont une mémoire autobiographique quasi parfaite (HSAM : Highly Superior Autobiographical Memory, c’est-à-dire la capacité de se souvenir en détail de presque chaque jour de leur vie).",
  "L’amnésie peut effacer des années sans toucher la personnalité.",
  "Des lésions ciblées peuvent supprimer un seul type de mémoire.",
  "On peut oublier un visage mais reconnaître une émotion.",
  "La musique peut réveiller des souvenirs chez des patients Alzheimer.",
  "Une odeur peut déclencher un souvenir très précis.",
  "Le cerveau peut apprendre sans conscience (apprentissage implicite).",
  "On peut avoir un souvenir sans savoir d’où il vient.",
  "La mémoire peut être améliorée par des stratégies, pas par la volonté seule.",
  "Les champions de mémoire n’ont pas un “meilleur cerveau”, mais de meilleures méthodes.",
  "Le cerveau consomme beaucoup d’énergie pour mémoriser.",
  "Rire aide à mémoriser.",
  "La mémoire aime les histoires plus que les listes.",
  "Écrire à la main améliore la mémorisation.",
  "Les gestes aident la mémoire.",
  "Les émotions négatives sont mieux mémorisées que les neutres.",
  "La répétition espacée est l’une des techniques les plus puissantes connues.",
  "La mémoire est liée à l’identité personnelle.",
  "Perdre la mémoire, c’est aussi perdre une partie de soi.",
  "La mémoire est imparfaite… et c’est ce qui la rend adaptable.",
];

export function getRandomFunFact() {
  const pool = [...funFacts];
  const { config } = useDeckStore.getState();
  if (config.includeCats) {
    pool.push(...catFunFacts);
  }
  if (config.includeAquatic) {
    pool.push(...aquaticFunFacts);
  }
  return pool[Math.floor(Math.random() * pool.length)];
}

const catFunFacts = [
  "Les chats ont une mémoire à court terme d’environ 16 heures, cela leur permet de se souvenir d’événements récents avec précision..",
  "Les chats peuvent se souvenir de personnes, d’animaux et de lieux pendant des années. Ils reconnaissent notamment : leur humain, leur maison, des expériences marquantes (positives ou négatives)",
  "Leur mémoire est très liée aux émotions. Une mauvaise expérience (peur, douleur) sera retenue beaucoup plus durablement qu’un événement neutre.",
  "Les chats utilisent une mémoire associative : bruit du sachet = nourriture, bruit de la caisse de transport = vétérinaire",
  "Les chats ont une excellente mémoire des habitudes et horaires : heure du repas, moment du câlin, routines du propriétaire",
  "Contrairement aux humains, les chats retiennent surtout : ce qui est utile pour eux, ce qui les concerne directement. Ils ignorent volontairement ce qui ne les intéresse pas.",
  "Grâce à leur mémoire spatiale, les chats peuvent : mémoriser leur territoire, retrouver leur maison sur de longues distances",
  "Les chats gardent une carte mentale de leur environnement : cachettes, sources de nourriture, zones “dangereuses”",
  "Des études montrent que les chats peuvent : reconnaître la voix de leur propriétaire, réagir différemment à des inconnus",
  "Une seule mauvaise expérience peut créer : une peur durable, une aversion (objet, lieu, personne)",
  "Les chats filtrent très bien l’information :ils gardent les événements utiles à leur survie,ils oublient le reste",
  "Les chats savent reconnaître leur nom… mais ne répondent pas toujours. Ce n’est pas un problème de mémoire, mais de motivation.",
  "Les jeunes chats ont une mémoire très plastique : apprentissage rapide, forte capacité d’adaptation",
  "Une des cartes chats a paraît surnaturelle... avez-vous deviné laquelle ?",
];

const aquaticFunFacts = [
  "Le mythe des “3 secondes de mémoire” est totalement faux. Les poissons rouges peuvent se souvenir d’un événement pendant plusieurs mois.",
  "Les poissons rouges peuvent apprendre à reconnaître leur humain, distinguer des formes, des couleurs, et même venir quand on les appelle (conditionnement sonore).",
  "Les poissons-archers, ceux qui tirent des jets d’eau pour faire tomber des insectes, peuvent reconnaître des visages humains avec une précision étonnante.",
  "Les labres nettoyeurs (petits poissons de récif) se souviennent pendant au moins 24 heures des clients qu’ils ont “arnaqués” (en mordillant au lieu de nettoyer). Ils évitent ensuite ces clients pour ne pas perdre leur réputation.",
  "Les saumons mémorisent l’odeur exacte de leur rivière natale et peuvent la retrouver des années plus tard, après des milliers de kilomètres.",
  "Les poulpes ont une mémoire à court et long terme, et peuvent résoudre des puzzles, ouvrir des bocaux, et même se souvenir de la solution plusieurs jours plus tard.",
  "Ils reconnaissent les humains individuellement et peuvent aimer ou détester certains soigneurs.",
  "Un poulpe peut apprendre en observant un autre poulpe — un comportement rare chez les animaux.",
  "Leur mémoire est distribuée : deux tiers de leurs neurones sont dans leurs bras, qui peuvent apprendre des choses indépendamment du cerveau central.",
  "Les dauphins ont la plus longue mémoire sociale connue chez les animaux : ils peuvent reconnaître le “sifflement signature” d’un ancien compagnon 20 ans plus tard.",
  "Ils se souviennent des alliances, des conflits, et des individus fiables ou non — un vrai Game of Thrones sous-marin.",
  "Les requins peuvent mémoriser des routes, des zones de chasse et des signaux visuels pendant des semaines.",
  "Certains requins de récif apprennent à reconnaître des plongeurs spécifiques et reviennent vers eux régulièrement.",
  "Les coquillages n’ont pas de cerveau, donc pas de mémoire au sens classique.",
  "Les escargots de mer (Aplysie) peuvent apprendre à associer un stimulus à une récompense ou une punition. Leur mémoire peut durer des jours, malgré un système nerveux minuscule.",
  "Les huîtres et moules n’ont pas de mémoire cognitive, mais elles ont une mémoire biologique : elles ajustent leur rythme d’ouverture/fermeture en fonction de cycles lumineux ou de marées passées.",
  "Les crabes peuvent se souvenir d’un danger pendant au moins 24 heures et modifier leur comportement.",
  "Les écrevisses montrent des réactions proches de l’anxiété après un stress, et leur mémoire du danger influence leur comportement futur.",
  "Des études montrent que certains poissons peuvent distinguer Bach de Stravinsky, et s’en souvenir.",
  "Certains poissons apprennent à associer une mélodie à un repas, et reviennent quand on rejoue la musique.",
];
